import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";

const roboto = Roboto({
  variable: "--font-geist-roboto",
  weight: "600",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Falaki's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} bg-gradient-to-r from-[#0a0f1c] to-[#1e293b] text-white min-h-screen`}
      >
        {children}
      </body>
    </html>
  );
}
